# Generated by Django 3.1.6 on 2021-05-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientacion', models.CharField(max_length=150, unique=True, verbose_name='Orientacion')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigPagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=150, unique=True, verbose_name='Color')),
                ('orientacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.orientationpag', verbose_name='Orientacion')),
            ],
        ),
    ]
