# Generated by Django 3.1.6 on 2021-05-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_orientationpag_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configpagina',
            name='color',
            field=models.CharField(max_length=150, verbose_name='Color'),
        ),
    ]
