# Generated by Django 3.1.6 on 2021-05-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_tendespectro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to='tendencias')),
                ('creada_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizada_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
        ),
    ]
